<?php
$css = array();

//CSS Sheets [the easy way]

//Description: [Darkness Default Value]

//Backgrounds:

//Body Background: 			[#000C1A]
$css['background1'] 	= '#0F0F0F'; //'#2C0000'; //Hot Pink

//Alert Bar Background: 	[#000C1A]
$css['background2'] 	= '#000000'; //'#000000'; //'#424242'; Purple

//Clock Background: 		[#001F33]
$css['background3'] 	= '#2C2C2C'; //'#131313'; //Hot Yellow

//Logout top line BG: 		[#031A33]
$css['background4'] 	= '#0F0F0F'; //'#222222';

//Logout Bottom line BG: 	[#000C1A]
$css['background5'] 	= '#1F1F1F'; //'#131313';

//Hover Highlight [This is only used in CSS once... Don't know where in SWC its used?]
$css['background6']		= '#FFFF00'; //'#60AF41';

//Menu Header Background	[#00243d]
$css['background7']		= '#1F1F1F'; //'#1F1F1F';

//Menu Alert Bar, Events Icons Dark Colour Background!
$css['background8']		= '#2C2C2C'; //'#2C2C2C' ;

//Table row hover highlight colour
$css['background9']		= '#242424';

//Font Colours:
//Body <a> Font Colour: 	[#CCCCCC]
//Note: also default body font color.
$css['afont1']			= '#C0C0C0'; //'#CCCCCC';

//Body <a> Hover Font:		[#888888]
$css['afont2'] 			= '#888888'; //'#888888';

//Header Font				[#000000]
$css['hfont1']			= '#000000';

//Alertbar top font: 		[#FFFFFF]
$css['alertfont1'] 		= '#C0C0C0'; //'#FFFFFF';

//Alertbar bottom font:		[#98B4C5]
$css['alertfont2'] 		= '#C0C0C0'; //'#CCCCCC';

//Top Bar <a>:				[#98B4C5]
$css['topbarfont1']		= '#C0C0C0'; //'#CCCCCC';

//Top Bar <a> Hover:		[#888888]
$css['topbarfont2'] 	= '#C0C0C0'; //'#888888';



//Borders:

//Top Menu Border Colour 	[#000C1A]
//Note: Usually same as Body BG Colour
$css['border1']			= '#000000'; //'#0A0A0A';

//Alertbar Border:			[#11465F]
$css['border2']			= '#000000'; //'#535353';

//Inventory Button selected Border:			[#FFFFCC]
$css['border3']			= '#FFFFCC';

//Menu Stuff
//Menu Highlight Colour [Where is this one used?]
$css['menu1']			= '#FFFFFF'; //'#888888';

//Forum Properties:
//Description Font Colour 	[#999999]
$css['forum1']			= '#FFFFFF'; //'#999999';

//Rules Redesign
//<a> colour for the rules menu
$css['afontrulesmenu']			= '#C0C0C0';

//active page (highlight) for the rules menu
$css['afontrulesmenuactive']   = '#FFFFCC';

//border of the 'Table of Contents'
$css['tocborder']			= '#848484';

//background of the 'Table of Contents'
$css['tocbackground']   = '#3C3C3C';
?>