<?php
$css = array();

//CSS Sheets [the easy way]

//Description: [Darkness Default Value]

//Backgrounds:

//Body Background: 			[#000C1A]
$css['background1'] 	= '#061300';

//Alert Bar Background: 	[#000C1A]
$css['background2'] 	= '#2B4A1E';

//Clock Background: 		[#001F33]
$css['background3'] 	= '#1A2E12';

//Logout top line BG: 		[#031A33]
$css['background4'] 	= '#1A2E12';

//Logout Bottom line BG: 	[#000C1A]
$css['background5'] 	= '#002C00';

//Hover Highlight [This is only used in CSS once... Don't know where in SWC its used?] [See Also: Highlight Font]
$css['background6']		= '#65E632';

//Menu Header Background	[#00243d]
$css['background7']		= '#021205';

//Menu Alert Bar, Events Icons Dark Colour Background!
$css['background8']		= '#002C00';

//Table row hover highlight colour
$css['background9']		= '#457830';

//Font Colours:
//Body <a> Font Colour: 	[#CCCCCC]
$css['afont1']			= '#CCCCCC';

//Body <a> Hover Font:		[#888888]
$css['afont2'] 			= '#888888';

//Highlight Font Color [This is only used in CSS once... Don't know where in SWC its used?]
$css['hfont1']			= '#000000';

//Alertbar top font: 		[#FFFFFF]
$css['alertfont1'] 		= '#FFFFFF';

//Alertbar bottom font:		[#98B4C5]
$css['alertfont2'] 		= '#5F8F50';

//Top Bar <a>:				[#98B4C5]
$css['topbarfont1']		= '#CCCCCC';

//Top Bar <a> Hover:		[#888888]
$css['topbarfont2'] 	= '#888888';

//Borders:

//Top Menu Border Colour 	[#000C1A]
//Note: Usually same as Body BG Colour
$css['border1']			= '#000C1A';

//Alertbar Border:			[#11465F]
$css['border2']			= '#3C5B2F';

//Inventory Button selected Border:			[#FFFFCC]
$css['border3']			= '#FFFFCC';

//Menu Stuff
//Menu Highlight Colour [Where is this one used?]
$css['menu1']			= '#56A349';

//Forum Properties:
//Description Font Colour 	[#999999]
$css['forum1']			= '#999999';

//Rules Redesign
//<a> colour for the rules menu
$css['afontrulesmenu']			= '#5F8F50';

//active page (highlight) for the rules menu
$css['afontrulesmenuactive']   = '#FFFFCC';

//border of the 'Table of Contents'
$css['tocborder']			= '#000C1A';

//background of the 'Table of Contents'
$css['tocbackground']   = '#3C5B2F';
?>