<?php
$css = array();

//CSS Sheets [the easy way]

//Description: [Darkness Default Value]

//Backgrounds:

//Body Background: 			[#000C1A]
$css['background1'] 	= '#1A0011';

//Alert Bar Background: 	[#000C1A]
$css['background2'] 	= '#990066';

//Clock Background: 		[#001F33]
$css['background3'] 	= '#5E003F';

//Logout top line BG: 		[#031A33]
$css['background4'] 	= '#7D0054';

//Logout Bottom line BG: 	[#000C1A]
$css['background5'] 	= '#5E003F';

//Hover Highlight [This is only used in CSS once... Don't know where in SWC its used?]
$css['background6']		= '#FFFFCC';

//Menu Header Background	[#00243d]
$css['background7']		= '#660066';

//Menu Alert Bar, Events Icons Dark Colour Background!
$css['background8']		= '#2C0000';

//Table row hover highlight colour
$css['background9']		= '#BA047D';

//Font Colours:
//Body <a> Font Colour: 	[#CCCCCC]
$css['afont1']			= '#CCCCCC';

//Body <a> Hover Font:		[#888888]
$css['afont2'] 			= '#888888';

//Header Font				[#000000]
$css['hfont1']			= '#000000';

//Alertbar top font: 		[#FFFFFF]
$css['alertfont1'] 		= '#FFFFFF';

//Alertbar bottom font:		[#98B4C5]
$css['alertfont2'] 		= '#98B4C5';

//Top Bar <a>:				[#98B4C5]
$css['topbarfont1']		= '#CCCCCC';

//Top Bar <a> Hover:		[#888888]
$css['topbarfont2'] 	= '#888888';

//Borders:

//Top Menu Border Colour 	[#000C1A]
//Note: Usually same as Body BG Colour
$css['border1']			= '#1A0011';

//Alertbar Border:			[#11465F]
$css['border2']			= '#C0006F';

//Inventory Button selected Border:			[#FFFFCC]
$css['border3']			= '#FFFFCC';

//Menu Stuff
//Menu Highlight Colour [Where is this one used?]
$css['menu1']			= '#256887';

//Forum Properties:
//Description Font Colour 	[#999999]
$css['forum1']			= '#999999';

//Rules Redesign
//<a> colour for the rules menu
$css['afontrulesmenu']			= '#98B4C5';

//active page (highlight) for the rules menu
$css['afontrulesmenuactive']   = '#B31E71';

//border of the 'Table of Contents'
$css['tocborder']			= '#1A0011';

//background of the 'Table of Contents'
$css['tocbackground']   = '#C0006F';
?>