<?php
$css = array();

//CSS Sheets [the easy way]

//Description: [Darkness Default Value]

//Backgrounds:

//Body Background: 			[#000C1A]
$css['background1'] 	= '#210000';

//Alert Bar Background: 	[#000C1A]
$css['background2'] 	= '#8F0808';

//Clock Background: 		[#001F33]
$css['background3'] 	= '#650B0B';

//Logout top line BG: 		[#031A33]
$css['background4'] 	= '#640000';

//Logout Bottom line BG: 	[#000C1A]
$css['background5'] 	= '#2E0000';

//Hover Highlight [This is only used in CSS once... Don't know where in SWC its used?]
$css['background6'] 	= '#DC0D0D';

//Menu Header Background	[#00243d]
$css['background7']		= '#7F1111';

//Menu Alert Bar, Events Icons Dark Colour Background!
$css['background8']		= '#680B0B';

//Table row hover highlight colour
$css['background9']		= '#B50909';

//Font Colours:
//Body <a> Font Colour: 	[#CCCCCC]
//Note: also default body font color.
$css['afont1']			= '#CCCCCC';

//Body <a> Hover Font:		[#888888]
$css['afont2'] 			= '#888888';

//Header Font				[#000000]
$css['hfont1']			= '#000000';

//Alertbar top font: 		[#FFFFFF]
$css['alertfont1'] 		= '#FFFFFF';

//Alertbar bottom font:		[#98B4C5]
$css['alertfont2'] 		= '#F17777';

//Top Bar <a>:				[#98B4C5]
$css['topbarfont1']		= '#CCCCCC';

//Top Bar <a> Hover:		[#888888]
$css['topbarfont2'] 	= '#888888';

//Borders:

//Top Menu Border Colour 	[#000C1A] -- Used at the extreme top of the page between the links at the top
//Note: Usually same as Body BG Colour
$css['border1']			= '#210000';

//Alertbar Border:			[#11465F]
$css['border2']			= '#3E0902';

//Inventory Button selected Border:			[#FFFFCC]
$css['border3']			= '#FFFFCC';

//Menu Stuff
//Menu Highlight Colour [Where is this one used?]
$css['menu1']			= '#CF3333';

//Forum Properties:
//Description Font Colour 	[#999999]
$css['forum1']			= '#999999';

//Rules Redesign
//<a> colour for the rules menu
$css['afontrulesmenu']			= '#F17777';

//active page (highlight) for the rules menu
$css['afontrulesmenuactive']   = '#EF1F1F';

//border of the 'Table of Contents'
$css['tocborder']			= '#210000';

//background of the 'Table of Contents'
$css['tocbackground']   = '#AD1D1D';
?>